# Generated by Django 5.0.1 on 2025-10-25 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('k8s_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_clusters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deployment',
            name='cluster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='k8s_management.cluster'),
        ),
        migrations.AddField(
            model_name='node',
            name='cluster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='k8s_management.cluster'),
        ),
        migrations.AddField(
            model_name='pod',
            name='cluster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pods', to='k8s_management.cluster'),
        ),
        migrations.AddField(
            model_name='service',
            name='cluster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='k8s_management.cluster'),
        ),
        migrations.AlterUniqueTogether(
            name='deployment',
            unique_together={('cluster', 'namespace', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='node',
            unique_together={('cluster', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='pod',
            unique_together={('cluster', 'namespace', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='service',
            unique_together={('cluster', 'namespace', 'name')},
        ),
    ]
