version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: devops_platform
      POSTGRES_USER: devops
      POSTGRES_PASSWORD: devops_secure_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U devops"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - devops-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - devops-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: >
      sh -c "python manage.py migrate &&
             python scripts/create_default_user.py &&
             daphne -b 0.0.0.0 -p 8000 devops_platform.asgi:application"
    volumes:
      - ./backend:/app
      - ansible_data:/app/ansible_data
      - terraform_data:/app/terraform_data
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://devops:devops_secure_pass@db:5432/devops_platform
      - DB_NAME=devops_platform
      - DB_USER=devops
      - DB_PASSWORD=devops_secure_pass
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_URL=redis://redis:6379/0
      - REDIS_HOST=redis
      - SECRET_KEY=django-insecure-dev-key-please-change-in-production-12345
      - DEBUG=True
      - ALLOWED_HOSTS=localhost,127.0.0.1,backend
      - ENCRYPTION_KEY=fernet-encryption-key-change-in-production-32bytes-base64==
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - devops-network

  celery:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: celery -A devops_platform worker -l info
    volumes:
      - ./backend:/app
      - ansible_data:/app/ansible_data
      - terraform_data:/app/terraform_data
    environment:
      - DATABASE_URL=postgresql://devops:devops_secure_pass@db:5432/devops_platform
      - DB_NAME=devops_platform
      - DB_USER=devops
      - DB_PASSWORD=devops_secure_pass
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_URL=redis://redis:6379/0
      - REDIS_HOST=redis
      - SECRET_KEY=django-insecure-dev-key-please-change-in-production-12345
      - ENCRYPTION_KEY=fernet-encryption-key-change-in-production-32bytes-base64==
    depends_on:
      - db
      - redis
      - backend
    networks:
      - devops-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - devops-network

networks:
  devops-network:
    driver: bridge

volumes:
  postgres_data:
  ansible_data:
  terraform_data:
