# Generated by Django 5.0.1 on 2025-10-25 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('hostname', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField()),
                ('port', models.IntegerField(default=22)),
                ('os_type', models.CharField(choices=[('linux', 'Linux'), ('windows', 'Windows'), ('macos', 'macOS')], default='linux', max_length=20)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('ssh_username', models.CharField(max_length=255)),
                ('ssh_password_encrypted', models.BinaryField(blank=True, null=True)),
                ('ssh_private_key_encrypted', models.BinaryField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('application_name', models.CharField(blank=True, max_length=255)),
                ('environment', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'machines',
                'ordering': ['-created_at'],
            },
        ),
    ]
