# Generated by Django 5.0.1 on 2025-10-25 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machines', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_machines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='machine',
            unique_together={('ip_address', 'port')},
        ),
    ]
