# Generated by Django 5.0.1 on 2025-10-25 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnsiblePlaybook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('deployment', 'Deployment'), ('configuration', 'Configuration'), ('maintenance', 'Maintenance'), ('security', 'Security'), ('monitoring', 'Monitoring')], default='deployment', max_length=50)),
                ('playbook_content', models.TextField(help_text='YAML content of the playbook')),
                ('inventory_content', models.TextField(blank=True, help_text='Inventory file content')),
                ('variables', models.JSONField(blank=True, default=dict, help_text='Default variables')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('timeout', models.IntegerField(default=3600, help_text='Timeout in seconds')),
                ('become', models.BooleanField(default=False, help_text='Run with sudo')),
                ('check_mode', models.BooleanField(default=False, help_text='Dry run mode')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_executed', models.DateTimeField(blank=True, null=True)),
                ('execution_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'ansible_playbooks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlaybookExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('target_hosts', models.JSONField(default=list, help_text='List of target host IPs')),
                ('variables', models.JSONField(blank=True, default=dict, help_text='Runtime variables')),
                ('output', models.TextField(blank=True)),
                ('error_output', models.TextField(blank=True)),
                ('return_code', models.IntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, help_text='Duration in seconds', null=True)),
                ('task_id', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'playbook_executions',
                'ordering': ['-started_at'],
            },
        ),
    ]
