# Generated by Django 5.0.1 on 2025-10-25 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('automation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ansibleplaybook',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_playbooks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='playbookexecution',
            name='executed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playbook_executions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='playbookexecution',
            name='playbook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='automation.ansibleplaybook'),
        ),
        migrations.AddIndex(
            model_name='playbookexecution',
            index=models.Index(fields=['-started_at'], name='playbook_ex_started_654136_idx'),
        ),
        migrations.AddIndex(
            model_name='playbookexecution',
            index=models.Index(fields=['playbook', '-started_at'], name='playbook_ex_playboo_bd0edd_idx'),
        ),
        migrations.AddIndex(
            model_name='playbookexecution',
            index=models.Index(fields=['status'], name='playbook_ex_status_d1057a_idx'),
        ),
    ]
