# Generated by Django 5.0.1 on 2025-10-25 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TerraformRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_type', models.CharField(choices=[('PLAN', 'Plan'), ('APPLY', 'Apply'), ('DESTROY', 'Destroy')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('variables', models.JSONField(blank=True, default=dict)),
                ('output', models.TextField(blank=True)),
                ('error_output', models.TextField(blank=True)),
                ('return_code', models.IntegerField(blank=True, null=True)),
                ('plan_output', models.TextField(blank=True, help_text='Terraform plan output')),
                ('resources_to_add', models.IntegerField(default=0)),
                ('resources_to_change', models.IntegerField(default=0)),
                ('resources_to_destroy', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, help_text='Duration in seconds', null=True)),
                ('task_id', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'terraform_runs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='TerraformWorkspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('environment', models.CharField(choices=[('development', 'Development'), ('staging', 'Staging'), ('production', 'Production')], max_length=50)),
                ('provider', models.CharField(choices=[('aws', 'AWS'), ('azure', 'Azure'), ('gcp', 'Google Cloud'), ('kubernetes', 'Kubernetes'), ('other', 'Other')], max_length=50)),
                ('terraform_version', models.CharField(default='1.6.0', max_length=20)),
                ('working_directory', models.CharField(default='/terraform', max_length=500)),
                ('terraform_code', models.TextField(help_text='Terraform configuration code')),
                ('variables', models.JSONField(blank=True, default=dict, help_text='Terraform variables')),
                ('state_backend', models.CharField(default='local', help_text='Backend type: local, s3, azurerm, gcs', max_length=50)),
                ('state_backend_config', models.JSONField(blank=True, default=dict)),
                ('last_plan_status', models.CharField(blank=True, max_length=50)),
                ('last_apply_status', models.CharField(blank=True, max_length=50)),
                ('resource_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'terraform_workspaces',
                'ordering': ['-created_at'],
            },
        ),
    ]
