# Generated by Django 5.0.1 on 2025-10-25 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('terraform', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='terraformrun',
            name='triggered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terraform_runs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='terraformworkspace',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workspaces', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='terraformrun',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='terraform.terraformworkspace'),
        ),
        migrations.AddIndex(
            model_name='terraformrun',
            index=models.Index(fields=['-started_at'], name='terraform_r_started_a11a4b_idx'),
        ),
        migrations.AddIndex(
            model_name='terraformrun',
            index=models.Index(fields=['workspace', '-started_at'], name='terraform_r_workspa_0b8830_idx'),
        ),
        migrations.AddIndex(
            model_name='terraformrun',
            index=models.Index(fields=['status'], name='terraform_r_status_1bb4e9_idx'),
        ),
    ]
