# Generated by Django 5.0.1 on 2025-10-25 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('display_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('kubernetes', 'Kubernetes'), ('monitoring', 'Monitoring'), ('logging', 'Logging'), ('cicd', 'CI/CD'), ('security', 'Security')], max_length=50)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('requires_token', models.BooleanField(default=False)),
                ('requires_username_password', models.BooleanField(default=False)),
                ('requires_api_key', models.BooleanField(default=False)),
                ('default_port', models.IntegerField(blank=True, null=True)),
                ('default_path', models.CharField(default='/', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'dashboards',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DashboardIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('error', 'Error')], default='inactive', max_length=20)),
                ('username_encrypted', models.BinaryField(blank=True, null=True)),
                ('password_encrypted', models.BinaryField(blank=True, null=True)),
                ('token_encrypted', models.BinaryField(blank=True, null=True)),
                ('api_key_encrypted', models.BinaryField(blank=True, null=True)),
                ('custom_config', models.JSONField(blank=True, default=dict)),
                ('auto_login_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_accessed', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dashboard_integrations',
                'ordering': ['-created_at'],
            },
        ),
    ]
