# Generated by Django 5.0.1 on 2025-10-25 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboards', '0001_initial'),
        ('k8s_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardintegration',
            name='cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_integrations', to='k8s_management.cluster'),
        ),
    ]
