# Generated by Django 5.0.1 on 2025-10-25 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboards', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardintegration',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_integrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dashboardintegration',
            name='dashboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='dashboards.dashboard'),
        ),
        migrations.AlterUniqueTogether(
            name='dashboardintegration',
            unique_together={('dashboard', 'cluster')},
        ),
    ]
